base:
  - iv2b.yaml

dataset:
  iv2b:
    # 6-band filter bank within [8,30] Hz.
    bands:
      - [8.0, 12.0]
      - [12.0, 16.0]
      - [16.0, 20.0]
      - [20.0, 24.0]
      - [24.0, 28.0]
      - [28.0, 30.0]

