base:
  - iv2b_stop_snn_pretrain.yaml
  - ../dataset/iv2b_w3_fb6.yaml

model:
  encoder:
    type: none

  snn:
    input_scale: 5.0
    v_threshold: 0.5

task:
  add_subject_onehot: true
  add_time_feature: true
  force_commit_last_step: true

project:
  out_dir: runs/s5_stop_distill_pretrain

